services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    container_name: todo-backend
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    container_name: todo-frontend
    volumes:
      - ./frontend:/app
    restart: always
